Added lots of features
LucidtechAI/las-sdk-java pull request #22
Opened 2021-04-30 13:15 UTC by augustak

2021-05-04 19:04 UTC, magnurud requested changes
Lot's of great changes here! I have not looked at the tests yet, but it seems like 
2 empty files src/test/java/AssetsTest.java src/test/java/Service.java have been added without any content.

2021-05-04 20:20 UTC, augustak commented
> Lot's of great changes here! I have not looked at the tests yet, but it seems like
> 2 empty files src/test/java/AssetsTest.java src/test/java/Service.java have been added without any content.

The files that are empty is being removed, not added

2021-05-04 20:54 UTC, augustak commented on src/main/java/ai/lucidtech/las/sdk/Client.java
> +        HttpUriRequest request = this.createAuthorizedRequest("PATCH", "/assets/" + assetId, body);
I think all options objects should be allowed to be null. This is now consistent across the entire SDK.

2021-05-04 20:54 UTC, augustak commented on src/main/java/ai/lucidtech/las/sdk/Client.java
> +        }
I think all options objects should be allowed to be null. This is now consistent across the entire SDK.

2021-05-05 09:38 UTC, magnurud approved these changes

2021-05-05 09:53 UTC, merged